version: 2.1
orbs:
  pulumi: pulumi/pulumi@2.0.0
  gcp-cli: circleci/gcp-cli@1.0.0
jobs:
  install_gcloud:
    executor: gcp-cli/default
    steps:
      - gcp-cli/install
  preview:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - pulumi/login:
          access-token: ${PULUMI_ACCESS_TOKEN}
      - run:
          name: Install dependencies
          command: |
            cd ~/project/infra/cloudrun
            python -m venv ~/project/infra/image/venv
            source ./venv/bin/activate
            pip install -r ~/project/infra/image/requirements.txt
      - pulumi/preview:
          stack: nimbinatus/docker-image-circleci/qa_${CIRCLE_BUILD_NUM}
          working_directory: ~/project/infra/image
      - pulumi/preview:
          stack: nimbinatus/circleci-pulumi/qa_${CIRCLE_BUILD_NUM}
          working_directory: ~/project/infra/cloudrun
      - pulumi/stack_output:
          stack: nimbinatus/circleci-pulumi/qa_${CIRCLE_BUILD_NUM}
          property_name: cloud_run_url
          env_var: TEST_URL
      - run:
          name: Test URL
          command: |
            curl --sSJL $TEST_URL/hello
      - pulumi/destroy:
          stack: nimbinatus/docker-image-circleci/qa_${CIRCLE_BUILD_NUM}
          working_directory: ~/project/infra/image
      - pulumi/destroy:
          stack: nimbinatus/circleci-pulumi/qa_${CIRCLE_BUILD_NUM}
          working_directory: ~/project/infra/cloudrun
      - pulumi/stack_rm:
          stack: nimbinatus/docker-image-circleci/qa_${CIRCLE_BUILD_NUM}
      - pulumi/stack_rm:
          stack: nimbinatus/circleci-pulumi/qa_${CIRCLE_BUILD_NUM}
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - pulumi/login:
          access-token: ${PULUMI_ACCESS_TOKEN}
      - run:
          name: Install dependencies
          command: |
            cd ~/project/infra/image
            python -m venv ~/project/infra/image/venv
            source ./venv/bin/activate
            pip install -r ~/project/infra/image/requirements.txt
            docker --version
            echo $GOOGLE_CREDENTIALS | gcloud auth configure-docker
      - pulumi/update:
          stack: nimbinatus/docker-image-circleci/dev
          working_directory: ~/project/infra/image
  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - pulumi/login
      - run:
          name: Install dependencies
          command: |
            cd ~/project/infra/cloudrun
            python -m venv ~/project/infra/cloudrun/venv
            source ./venv/bin/activate
            pip install -r ~/project/infra/cloudrun/requirements.txt
      - pulumi/update:
          stack: nimbinatus/circleci-pulumi/dev
          working_directory: ~/project/infra/cloudrun
workflows:
  version: 2.1
  preview:
    jobs:
      - install_gcloud
      - preview:
          filters:
            branches:
              ignore:
                - main
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main