version: 2.1
orbs:
  pulumi: pulumi/pulumi@2.0.0
  gcp-cli: circleci/gcp-cli@1.0.0
jobs:
  preview:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - pulumi/login:
          access-token: ${PULUMI_ACCESS_TOKEN}
      - run:
          name: Install dependencies
          command: |
            cd ~/project/infra/cloudrun
            python -m venv ~/project/infra/image/venv
            source ./venv/bin/activate
            pip install -r ~/project/infra/image/requirements.txt
      - run:
          name: Install and init gcloud
          command: |
            cd ~/
            curl -o gcp-cli.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz
            tar -xzf gcp-cli.tar.gz
            echo ${GOOGLE_CREDENTIALS} | base64 --decode --ignore-garbage > ${HOME}/project/gcp/creds.json
            ./google-cloud-sdk/install.sh  --quiet
            echo 'export PATH=$PATH:~/google-cloud-sdk/bin:~/.local/bin' >> $BASH_ENV
            source $BASH_ENV
            gcloud auth activate-service-account --key-file ${HOME}/project/gcp/creds.json
      - pulumi/preview:
          stack: nimbinatus/docker-image-circleci/qa_${CIRCLE_BUILD_NUM}
          working_directory: ~/project/infra/image
      - pulumi/preview:
          stack: nimbinatus/circleci-pulumi/qa_${CIRCLE_BUILD_NUM}
          working_directory: ~/project/infra/cloudrun
      - pulumi/stack_output:
          stack: nimbinatus/circleci-pulumi/qa_${CIRCLE_BUILD_NUM}
          property_name: cloud_run_url
          env_var: TEST_URL
      - run:
          name: Test URL
          command: |
            curl --sSJL $TEST_URL/hello
      - pulumi/destroy:
          stack: nimbinatus/docker-image-circleci/qa_${CIRCLE_BUILD_NUM}
          working_directory: ~/project/infra/image
      - pulumi/destroy:
          stack: nimbinatus/circleci-pulumi/qa_${CIRCLE_BUILD_NUM}
          working_directory: ~/project/infra/cloudrun
      - pulumi/stack_rm:
          stack: nimbinatus/docker-image-circleci/qa_${CIRCLE_BUILD_NUM}
      - pulumi/stack_rm:
          stack: nimbinatus/circleci-pulumi/qa_${CIRCLE_BUILD_NUM}
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - pulumi/login:
          access-token: ${PULUMI_ACCESS_TOKEN}
      - run:
          name: Install dependencies
          command: |
            cd ~/project/infra/image
            python -m venv ~/project/infra/image/venv
            source ./venv/bin/activate
            pip install -r ~/project/infra/image/requirements.txt
            docker --version
      - run:
          name: Install and init gcloud
          command: |
            cd ~/
            curl -o gcp-cli.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz
            tar -xzf gcp-cli.tar.gz
            ./google-cloud-sdk/install.sh  --quiet
            echo 'export PATH=$PATH:~/google-cloud-sdk/bin:~/.local/bin' >> $BASH_ENV
            source $BASH_ENV
            gcloud version
      - run:
          name: Set up GCP
          command: |
            echo ${GOOGLE_CREDENTIALS} >> ~/project/creds.json
            gcloud auth activate-service-account --key-file ~/project/creds.json
            gcloud auth configure-docker
            gcloud auth list --filter=status:ACTIVE --format="value(account)"
            cat ~/.docker/config.json
      - pulumi/update:
          stack: nimbinatus/docker-image-circleci/dev
          working_directory: ~/project/infra/image
  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - pulumi/login
      - run:
          name: Install dependencies
          command: |
            cd ~/project/infra/cloudrun
            python -m venv ~/project/infra/cloudrun/venv
            source ./venv/bin/activate
            pip install -r ~/project/infra/cloudrun/requirements.txt
      - run:
          name: Install and init gcloud
          command: |
            cd ~/
            curl -o gcp-cli.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz
            tar -xzf gcp-cli.tar.gz
            echo ${GOOGLE_CREDENTIALS} | base64 --decode --ignore-garbage > ${HOME}/project/gcp/creds.json
            ./google-cloud-sdk/install.sh  --quiet
            echo 'export PATH=$PATH:~/google-cloud-sdk/bin:~/.local/bin' >> $BASH_ENV
            source $BASH_ENV
            gcloud auth activate-service-account --key-file ${HOME}/project/gcp/creds.json
      - pulumi/update:
          stack: nimbinatus/circleci-pulumi/dev
          working_directory: ~/project/infra/cloudrun
workflows:
  version: 2.1
  preview:
    jobs:
      - preview:
          filters:
            branches:
              ignore:
                - main
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main